import os
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
 b=p.chromium.launch(headless=True, executable_path=os.environ.get('CHROMIUM_BINARY') or '/usr/bin/chromium', args=['--no-sandbox','--allow-file-access-from-files'])
 page=b.new_page(viewport={'width':1440,'height':900},device_scale_factor=1)
 errors=[]
 page.on('pageerror',lambda err: errors.append(str(err)))
 page.goto(os.environ.get('APP_URL', 'http://127.0.0.1:8765/web/'),wait_until='networkidle')
 print('TITLE',page.title())
 print('HOME',page.locator('h1').first.inner_text())
 page.screenshot(path='/mnt/data/aplus-accelerator-preview.png',full_page=True)
 page.get_by_role('button',name='+ 새 과목').click()
 page.locator('[name="name"]').fill('촉매반응공학')
 page.locator('[name="characteristics"]').fill('수식·계산 중심, 올해 강의안 우선')
 page.locator('#modalForm button[type="submit"]').click()
 page.wait_for_timeout(180)
 print('COURSE',page.get_by_text('촉매반응공학').count())
 page.get_by_role('button',name='+ 학년도').first.click()
 page.locator('[name="professor"]').fill('예시 교수')
 page.locator('[name="notes"]').fill('올해 강의 범위 중심')
 page.locator('#modalForm button[type="submit"]').click()
 page.wait_for_timeout(180)
 page.get_by_role('button',name='강의자료함').click()
 page.get_by_role('button',name='+ 자료 등록').click()
 page.locator('[name="type"]').select_option('transcript')
 page.locator('[name="title"]').fill('5주차 녹취 전사본')
 page.locator('[name="text"]').fill('5주차에서는 물질전달 저항의 의미를 설명합니다.\n\n상세 내용은 강의 PDF를 참고하세요.')
 page.locator('#modalForm button[type="submit"]').click()
 page.wait_for_timeout(180)
 print('SOURCES',page.get_by_text('5주차 녹취 전사본').count())
 page.get_by_role('button',name='자료 제작실').click()
 print('STUDIO',page.locator('#requestPreview').inner_text()[:310])
 page.locator('#createJob').click()
 page.wait_for_timeout(100)
 page.get_by_role('button',name='작업 기록',exact=True).first.click()
 print('JOB VIEW',page.locator('h1').first.inner_text())
 page.get_by_role('button',name='정리본',exact=True).click()
 page.get_by_role('button',name='+ 정리본 작성').click()
 page.locator('[name="title"]').fill('5주차 정리본')
 page.locator('[name="content"]').fill('# 5주차\n외부 물질전달 개념')
 page.locator('#modalForm button[type="submit"]').click()
 page.wait_for_timeout(100)
 print('EDITOR',page.locator('#noteContent').input_value())
 page.locator('#noteContent').fill('# 5주차\n새 내용')
 page.locator('#saveNote').click()
 page.wait_for_timeout(100)
 print('SAVED',page.get_by_text('v2').count())
 page.reload(wait_until='networkidle')
 print('PERSIST',page.get_by_text('v2').count())
 print('JS ERRORS',errors)
 b.close()
 if errors: raise RuntimeError('Browser had JS errors')
