import {SOURCE_TYPES,MODES,DEFAULT_PRESETS,id,normalizeText,safeText as e,makeRequest,validateOffering,validateNote,markStep,nextStep} from '../domain/core.mjs';
import * as store from './db.js';
const el=document.querySelector('#app'),crumb=document.querySelector('#crumb'),toastEl=document.querySelector('#toast');
let data={courses:[],offerings:[],sources:[],notes:[],jobs:[],outlines:[]};
let view='home',courseId='',offeringId='',mode='detailed_note',scope='전체',detailKey='',sourceFilter='all',search='';
const obj=(key)=>data[key]||[];
const course=(cid)=>obj('courses').find(x=>x.id===cid);const offering=(oid)=>obj('offerings').find(x=>x.id===oid);
const current=()=>offering(offeringId)||obj('offerings').find(x=>x.courseId===courseId);
function notify(msg){toastEl.textContent=msg;toastEl.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>toastEl.classList.remove('show'),2600);}
async function persist(key){await store.put(key,data[key]);}
function options(arr,value,label){return arr.map(x=>`<option value="${e(String(value(x)))}">${e(String(label(x)))}</option>`).join('');}
function pagehead(title,sub,button=''){return `<div class="page-head"><div><div class="eyebrow">A+ ACCELERATOR</div><h1>${e(title)}</h1><p class="sub">${e(sub)}</p></div>${button}</div>`;}
function currentSelector(){const opts=obj('offerings').map(o=>({id:o.id,name:`${course(o.courseId)?.name||'삭제된 과목'} · ${o.year}-${o.term} ${o.professor?'· '+o.professor:''}`}));return opts.length?`<label class="field" style="max-width:410px"><span style="font-size:12px;font-weight:700">현재 강의</span><select id="offeringSelect">${options(opts,x=>x.id,x=>x.name)}</select></label>`:'<p class="notice">과목과 학년도별 강의를 먼저 등록해야 해.</p>';}
function empty(title,description){return `<div class="empty"><b>${e(title)}</b>${e(description)}</div>`;}
function courseCards(){return obj('courses').length?`<div class="course-grid">${obj('courses').map(c=>{const off=obj('offerings').filter(x=>x.courseId===c.id).sort((a,b)=>b.year-a.year);return `<article class="course"><div class="course-head"><span class="pill">과목 프로필</span><button data-action="newOffering" data-id="${e(c.id)}" class="ghost small">+ 학년도</button></div><div class="course-title">${e(c.name)}</div><p class="muted">${e(c.characteristics||'과목 특성을 아직 등록하지 않았어.')}</p><div class="flexwrap" style="margin-top:16px">${off.length?off.map(o=>`<button data-action="selectOffering" data-id="${e(o.id)}" class="tag" title="이 강의 선택">${e(o.year)}-${e(o.term)} · ${e(o.professor||'교수 미지정')}</button>`).join(''):'<span class="tag warning">개설 강의 등록 필요</span>'}</div><div class="mini-actions" style="margin-top:16px"><button data-action="editCourse" data-id="${e(c.id)}" class="ghost small">프로필 수정</button></div></article>`}).join('')}</div>`:empty('과목을 아직 등록하지 않았어','과목을 등록하고 현재 학년도 강의를 추가하면 돼.');}
function home(){return pagehead('공부를 더 빠르고, 정확하게.','과목의 맥락을 기억하고 GPT 작업 요청을 자동으로 준비해.','<button class="primary" data-action="newCourse">+ 새 과목</button>')+
 `<div class="cards"><div class="card"><div class="statlabel">내 과목</div><div class="statnum">${obj('courses').length}</div><div class="statnote">학기별 개설 기록 ${obj('offerings').length}개</div></div><div class="card"><div class="statlabel">등록 자료</div><div class="statnum">${obj('sources').length}</div><div class="statnote">전사본·강의자료 포함</div></div><div class="card"><div class="statlabel">정리본</div><div class="statnum">${obj('notes').length}</div><div class="statnote">작업 기록 ${obj('jobs').length}건</div></div></div>`+
 `<div class="kpi-strip"><div><h2>한 문장으로 시작하는 학습자료 제작</h2><p>ChatGPT 플러그인 연결 후에는 자료 검색·정리·저장까지 이어서 진행하도록 설계돼.</p></div><button class="primary" data-view="studio">제작실 열기 →</button></div>`+
 `<div class="split-head"><h2 class="section-title">내 과목</h2><button class="ghost small" data-view="courses">전체 보기 →</button></div>${courseCards()}`+
 `<div class="split-head"><h2 class="section-title">최근 작업</h2><button class="ghost small" data-view="jobs">작업 기록 →</button></div>${jobItems(obj('jobs').slice(-3).reverse())}`;
}
function courses(){return pagehead('내 과목','과목 특성은 공통으로, 교수·시험·자료는 학년도별로 구분해 저장해.','<button class="primary" data-action="newCourse">+ 과목 등록</button>')+courseCards();}
function sourceItems(arr){return arr.length?`<div class="list">${arr.map(s=>{const o=offering(s.offeringId);return `<article class="list-item"><div class="list-icon">${s.type==='transcript'?'≡':s.type==='past_exam'?'✎':'▤'}</div><div class="list-body"><b>${e(s.title)}</b><small>${e(SOURCE_TYPES[s.type])} · ${e(course(o?.courseId)?.name||'알 수 없음')} ${e(o?.year||'')} - ${e(o?.term||'')} · ${e(s.fileName||'직접 입력')}</small></div><span class="tag ${s.extractStatus==='ready'?'ready':'warning'}">${s.extractStatus==='ready'?'텍스트 준비':'추출 필요'}</span><button class="ghost small" data-action="inspectSource" data-id="${e(s.id)}">확인</button></article>`}).join('')}</div>`:empty('자료가 없어','TXT·MD 전사본을 올리거나 강의자료를 등록해 줘.');}
function sources(){const src=obj('sources').filter(s=>(sourceFilter==='all'||s.type===sourceFilter) && (!search||(s.title+' '+s.fileName+' '+s.text).toLowerCase().includes(search.toLowerCase())));return pagehead('강의자료함','녹음 파일이 아닌 전사본(TXT·MD 또는 텍스트 붙여넣기)을 받도록 설계했어.','<button class="primary" data-action="newSource">+ 자료 등록</button>')+`<div class="source-filter"><select id="sourceFilter"><option value="all">전체 자료 유형</option>${options(Object.keys(SOURCE_TYPES),x=>x,x=>SOURCE_TYPES[x])}</select><input id="sourceSearch" aria-label="자료 검색" placeholder="파일명·본문 검색" value="${e(search)}"/></div>`+sourceItems(src)+`<p class="hint" style="margin-top:18px">이 프로토타입은 TXT·MD 본문과 직접 입력한 텍스트를 검색해. PDF·DOCX·PPTX는 업로드 목록에 등록되지만 텍스트 추출이 완료되지 않았음을 표시하며, 원본 파일의 지속 저장과 페이지 검색은 Sites 연동 후 검증해야 해.</p>`;}
function studio(){let o=current();const c=course(o?.courseId);const sources=obj('sources');let result=o?makeRequest({course:c,offering:o,sources,mode,scope}):null;
 return pagehead('자료 제작실','기존의 긴 프롬프트는 자동 적용하고, GPT에 전달할 명령만 준비해.','<button class="ghost" data-view="jobs">작업 기록 보기</button>')+`<div class="studio-layout"><section class="card"><div class="steps"><span class="active">01 학년도 선택</span><span>→</span><span>02 제작 유형</span><span>→</span><span>03 GPT 요청</span></div>${currentSelector()}<h3 style="margin:19px 0 8px">무엇을 만들까?</h3><div class="choice-grid">${Object.entries(MODES).map(([k,v])=>`<button class="choice ${k===mode?'selected':''}" data-action="mode" data-id="${e(k)}">${e(v)}</button>`).join('')}</div><div class="field"><label for="scopeInput">제작 범위</label><input id="scopeInput" placeholder="예: 5주차 / 중간고사 전체" value="${e(scope)}"/></div><div class="notice">AI 모델은 이 웹사이트에서 자동 실행하지 않아. 아래 요청을 복사한 뒤 ChatGPT의 에쁠가속기 플러그인에 보내야 해.</div><div style="margin-top:18px" class="row"><button class="primary" id="copyRequest" ${!o?'disabled':''}>GPT 요청 복사</button><button class="ghost" id="createJob" ${!o?'disabled':''}>작업 기록 만들기</button></div></section><aside class="card"><h3 style="margin-top:0">자동 적용 규칙</h3><p class="muted">${e(MODES[mode])} · ${e(DEFAULT_PRESETS[mode].format)}</p><div class="list">${DEFAULT_PRESETS[mode].rules.map((r,i)=>`<div class="row"><span class="tag">${i+1}</span><span class="hint">${e(r)}</span></div>`).join('')}</div><h3>자료 준비 상태</h3><div class="flexwrap">${(result?.sourceIds||[]).length?`<span class="tag ready">자료 후보 ${result.sourceIds.length}건</span>`:'<span class="tag warning">선택된 자료 없음</span>'}</div>${(result?.warnings||[]).map(x=>`<p class="hint" style="color:#a7771e">⚠ ${e(x)}</p>`).join('')}<h3>GPT 요청 미리보기</h3><div id="requestPreview" class="code-preview">${e(result?.text||'학년도별 강의를 먼저 등록해.')}</div></aside></div>`;}
function notes(){let rows=obj('notes');return pagehead('Study Note','GPT가 만든 결과물을 웹에서 열어 확인하고 직접 저장할 수 있도록 하는 화면.','<button class="primary" data-action="newNote">+ 정리본 작성</button>')+(rows.length?`<div class="list">${rows.map(n=>{const o=offering(n.offeringId);return `<article class="list-item"><div class="list-icon">▥</div><div class="list-body"><b>${e(n.title)}</b><small>${e(course(o?.courseId)?.name||'과목 없음')} · ${e(o?.year||'')}-${e(o?.term||'')} · ${e(n.updatedAt?.slice(0,10)||'')}</small></div><span class="tag ready">v${e(n.version||1)}</span><button class="ghost small" data-action="editNote" data-id="${e(n.id)}">편집</button></article>`}).join('')}</div>`:empty('정리본이 없어','GPT 결과를 붙여넣거나 직접 작성할 수 있어.'));
}
function jobItems(arr){return arr.length?`<div class="list">${arr.map(j=>{const o=offering(j.offeringId);return `<article class="list-item"><div class="list-icon">◴</div><div class="list-body"><b>${e(MODES[j.mode]||j.mode)}</b><small>${e(course(o?.courseId)?.name||'')} · ${e(j.scope||'전체')} · ${e(j.createdAt?.slice(0,16).replace('T',' ')||'')}</small></div><span class="tag ${j.status==='complete'?'ready':'warning'}">${j.status==='complete'?'완료':'다음: '+nextStep(j)}</span><button data-action="inspectJob" data-id="${e(j.id)}" class="ghost small">상태·요청</button></article>`}).join('')}</div>`:empty('작업 기록이 없어','제작실에서 작업 기록을 만들면 여기에서 이어가기 요청을 준비할 수 있어.');}
function jobs(){return pagehead('작업 기록','진행 중인 GPT 작업을 추적하고 중복 생성을 방지하는 데 사용하는 화면.','<button class="ghost" data-view="studio">제작실로 이동 →</button>')+jobItems([...obj('jobs')].reverse());}
function editor(){const n=obj('notes').find(x=>x.id===detailKey);if(!n){view='notes';return notes();}return pagehead('정리본 편집','임시 저장소에서 문서를 작성할 수 있어. Sites 저장소 연결 전이므로 다른 사람에게 자동 공유되지는 않아.',`<button class="ghost" data-view="notes">← 목록</button>`)+`<div class="note-editor"><section class="card"><h3>문서 정보</h3><div class="field"><label>제목</label><input id="noteTitle" value="${e(n.title)}" /></div><div class="field"><label>버전</label><span class="tag">v${e(n.version||1)}</span></div><p class="hint">Markdown으로 입력한 내용은 원본 텍스트로 보존돼. 복잡한 수식·Word OMML 출력은 다음 단계에서 별도 검증해야 해.</p></section><section class="card"><div class="row" style="margin-bottom:12px"><h3 style="margin:0">본문</h3><div class="spacer"></div><button class="primary small" id="saveNote">수정 저장</button><button class="ghost small" id="downloadNote">.md 받기</button></div><textarea class="large" id="noteContent" aria-label="정리본 본문">${e(n.content)}</textarea></section></div>`;}
function render(){if(!courseId&&obj('courses').length)courseId=obj('courses')[0].id;if(!offeringId&&obj('offerings').length)offeringId=obj('offerings')[0].id;const titles={home:'대시보드',courses:'내 과목',sources:'강의자료함',studio:'자료 제작실',notes:'정리본',jobs:'작업 기록',editor:'정리본 편집'};crumb.textContent=titles[view];document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view||view==='editor'&&b.dataset.view==='notes'));el.innerHTML=({home,courses,sources,studio,notes,jobs,editor}[view]||home)();const sel=document.querySelector('#offeringSelect');if(sel)sel.value=offeringId;const fil=document.querySelector('#sourceFilter');if(fil)fil.value=sourceFilter;}
function showDialog(title,html,save){const d=document.querySelector('#modal'),f=document.querySelector('#modalForm');document.querySelector('#modalTitle').textContent=title;document.querySelector('#modalBody').innerHTML=html;document.querySelector('#modalForm .primary').style.display='';f.onsubmit=async ev=>{ev.preventDefault();try{await save(new FormData(f));d.close();render();notify('저장했어.');}catch(err){notify(err.message);}};d.showModal();}
function addCourse(existing){showDialog(existing?'과목 프로필 수정':'새 과목 등록',`<div class="field"><label>과목명 *</label><input name="name" required maxlength="80" value="${e(existing?.name||'')}"></div><div class="field"><label>과목 특성 (개념·수식·암기 등)</label><textarea name="characteristics">${e(existing?.characteristics||'')}</textarea></div><div class="field"><label>기본 자료 제작 선호</label><select name="preferredMode">${options(Object.keys(MODES),x=>x,x=>MODES[x])}</select></div>`,async f=>{const name=normalizeText(f.get('name'));if(!name)throw Error('과목명이 필요해.');if(existing){Object.assign(existing,{name,characteristics:String(f.get('characteristics')),preferredMode:String(f.get('preferredMode'))});}else{const c={id:id('course'),name,characteristics:String(f.get('characteristics')),preferredMode:String(f.get('preferredMode')),createdAt:new Date().toISOString()};obj('courses').push(c);courseId=c.id;}await persist('courses');});document.querySelector('[name="preferredMode"]').value=existing?.preferredMode||'detailed_note';}
function addOffering(cid){if(!obj('courses').length){notify('과목을 먼저 등록해.');return;}const selected=cid||courseId||obj('courses')[0].id;showDialog('학년도별 강의 등록',`<div class="field"><label>과목</label><select name="courseId">${options(obj('courses'),x=>x.id,x=>x.name)}</select></div><div class="form-grid"><div class="field"><label>학년도 *</label><input type="number" name="year" min="1990" max="2100" required value="2026"></div><div class="field"><label>학기 *</label><select name="term"><option value="1">1학기</option><option value="2">2학기</option><option value="여름">여름</option><option value="겨울">겨울</option></select></div></div><div class="field"><label>교수</label><input name="professor" maxlength="100"></div><div class="field"><label>해당 학기 강의·시험 특성</label><textarea name="notes" placeholder="시험 유형, 중요 공지, 강의 특성. 공식 근거가 없으면 추정임을 밝혀줘."></textarea></div>`,async f=>{const o=validateOffering({id:id('offering'),courseId:f.get('courseId'),year:Number(f.get('year')),term:f.get('term'),professor:normalizeText(f.get('professor')),notes:normalizeText(f.get('notes')),createdAt:new Date().toISOString()});if(obj('offerings').some(x=>x.courseId===o.courseId&&x.year===o.year&&String(x.term)===String(o.term)&&x.professor===o.professor))throw Error('같은 강의가 이미 있어.');obj('offerings').push(o);courseId=o.courseId;offeringId=o.id;await persist('offerings');});document.querySelector('[name="courseId"]').value=selected;document.querySelector('[name="term"]').value='2';}
function addSource(){if(!obj('offerings').length){notify('학년도 강의를 먼저 등록해.');return;}showDialog('학습 자료 등록',`<div class="field"><label>등록할 강의</label><select name="offeringId">${options(obj('offerings'),x=>x.id,x=>`${course(x.courseId)?.name||''} · ${x.year}-${x.term}`)}</select></div><div class="field"><label>자료 종류</label><select name="type">${options(Object.keys(SOURCE_TYPES),x=>x,x=>SOURCE_TYPES[x])}</select></div><div class="field"><label>자료 제목 *</label><input name="title" required placeholder="예: Week 5 물질전달 강의자료"></div><div class="field"><label>텍스트 파일 (TXT·MD / 선택)</label><input type="file" name="file" accept=".txt,.md,.csv,.pdf,.docx,.pptx"/><small>PDF·DOCX·PPTX의 내용 추출은 현재 데모에서 지원하지 않음.</small></div><div class="field"><label>추출된 텍스트 또는 전사본 내용</label><textarea name="text" rows="6" placeholder="전사본 원문을 여기에 붙여넣어도 돼."></textarea></div><div class="field"><label>참고 연도·출처·주의점</label><input name="provenance" placeholder="예: 2025 기출, 학생 제공 자료"></div>`,async f=>{const file=f.get('file');let text=normalizeText(f.get('text')),fileName='';if(file instanceof File&&file.size){fileName=file.name;const ext=file.name.split('.').pop().toLowerCase();if(['txt','md','csv'].includes(ext)){text=await file.text();if(file.size>4e6)throw Error('4MB 이하의 텍스트 파일만 업로드해.');}}const source={id:id('source'),offeringId:String(f.get('offeringId')),type:String(f.get('type')),title:normalizeText(f.get('title')),fileName,provenance:normalizeText(f.get('provenance')),text,extractStatus:text?'ready':'pending',createdAt:new Date().toISOString()};if(!source.title)throw Error('제목이 필요해.');obj('sources').push(source);await persist('sources');});document.querySelector('[name="offeringId"]').value=offeringId||obj('offerings')[0].id;}
function addNote(){if(!obj('offerings').length){notify('강의를 먼저 등록해.');return;}showDialog('새 정리본',`<div class="field"><label>대상 강의</label><select name="offeringId">${options(obj('offerings'),x=>x.id,x=>`${course(x.courseId)?.name||''} · ${x.year}-${x.term}`)}</select></div><div class="field"><label>제목 *</label><input name="title" required placeholder="예: 5주차 물질전달 정리"></div><div class="field"><label>본문 (ChatGPT 결과 붙여넣기 가능)</label><textarea name="content" rows="9"></textarea></div>`,async f=>{const n={id:id('note'),offeringId:String(f.get('offeringId')),title:normalizeText(f.get('title')),content:String(f.get('content')),version:1,updatedAt:new Date().toISOString()};const errs=validateNote(n);if(errs.length)throw Error(errs.join(', '));obj('notes').push(n);detailKey=n.id;view='editor';await persist('notes');});document.querySelector('[name="offeringId"]').value=offeringId||obj('offerings')[0].id;}
function blobDownload(content,name,mime='application/json'){const blob=new Blob([content],{type:mime});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function exportAll(){blobDownload(JSON.stringify({app:'에쁠가속기',schemaVersion:1,exportedAt:new Date().toISOString(),records:await store.all()},null,2),'aplus-accelerator-backup.json');notify('현재 브라우저 데이터 백업을 다운로드했어.');}
async function inspect(id){const s=obj('sources').find(x=>x.id===id);if(!s)return;showDialog('자료 정보',`<div class="field"><label>${e(s.title)}</label><span class="hint">${e(SOURCE_TYPES[s.type])} · ${e(s.fileName||'직접 입력')} · ${e(s.provenance||'출처 미등록')}</span></div><div class="field"><label>추출된 원문 (${s.text.length}자)</label><textarea rows="11" disabled>${e(s.text||'텍스트 추출이 아직 안 되었어.')}</textarea></div>`,async()=>{});document.querySelector('#modalForm .primary').style.display='none';}
function inspectJob(jid){const j=obj('jobs').find(x=>x.id===jid);if(!j)return;let o=offering(j.offeringId),c=course(o?.courseId);let req=makeRequest({course:c,offering:o,sources:obj('sources'),mode:j.mode,scope:j.scope,jobId:j.id});showDialog('GPT 작업 상세',`<p class="muted">${e(MODES[j.mode])} · 완료 단계 ${e((j.completedSteps||[]).join(', ')||'없음')} · 다음: ${e(nextStep(j))}</p><div class="field"><label>GPT 요청문</label><textarea rows="10" readonly id="jobPrompt">${e(req.text)}</textarea></div><button type="button" class="ghost" id="copyJob">요청문 복사</button><div class="field" style="margin-top:18px"><label>완료된 단계 직접 기록 (자동 완료 처리 아님)</label><select name="step"><option value="">그대로 두기</option>${options(['context','sources','outline','generate','verify','save'],x=>x,x=>x)}</select></div>`,async f=>{const step=f.get('step');if(step){Object.assign(j,markStep(j,step));await persist('jobs');}});document.querySelector('#copyJob').onclick=async()=>{await navigator.clipboard.writeText(req.text);notify('복사했어.');};}
document.addEventListener('click',async ev=>{const b=ev.target.closest('button');if(!b)return;if(b.dataset.view){view=b.dataset.view;render();return;}const action=b.dataset.action,aid=b.dataset.id;
 if(action==='newCourse')addCourse();if(action==='editCourse')addCourse(course(aid));if(action==='newOffering')addOffering(aid);if(action==='selectOffering'){offeringId=aid;courseId=offering(aid)?.courseId;view='studio';render();}if(action==='newSource')addSource();if(action==='inspectSource')inspect(aid);if(action==='mode'){mode=aid;render();}if(action==='newNote')addNote();if(action==='editNote'){detailKey=aid;view='editor';render();}if(action==='inspectJob')inspectJob(aid);
 if(b.id==='exportBtn')await exportAll();if(b.id==='closeModal')document.querySelector('#modal').close();
 if(b.id==='saveNote'){const n=obj('notes').find(x=>x.id===detailKey);const title=document.querySelector('#noteTitle').value.trim(),content=document.querySelector('#noteContent').value;const errors=validateNote({...n,title,content});if(errors.length){notify(errors.join(', '));return;}n.title=title;n.content=content;n.version=(n.version||1)+1;n.updatedAt=new Date().toISOString();await persist('notes');render();notify('새 버전으로 저장했어.');}
 if(b.id==='downloadNote'){const n=obj('notes').find(x=>x.id===detailKey);blobDownload(document.querySelector('#noteContent').value,`${n.title.replace(/[\\/:*?"<>|]/g,'_')}.md`,'text/markdown;charset=utf-8');}
 if(b.id==='copyRequest'){const o=current();const req=makeRequest({course:course(o.courseId),offering:o,sources:obj('sources'),mode,scope});try{await navigator.clipboard.writeText(req.text);notify('GPT 요청문을 복사했어.');}catch{notify('복사 권한이 없어. 미리보기 내용을 선택해 복사해.');}}
 if(b.id==='createJob'){const o=current();if(!o)return;const j={id:id('job'),offeringId:o.id,mode,scope,completedSteps:[],status:'pending',createdAt:new Date().toISOString()};obj('jobs').push(j);await persist('jobs');notify('작업 기록을 만들었어. GPT 요청은 별도로 실행해야 해.');}
});
document.addEventListener('change',ev=>{if(ev.target.id==='offeringSelect'){offeringId=ev.target.value;courseId=offering(offeringId)?.courseId;render();}if(ev.target.id==='sourceFilter'){sourceFilter=ev.target.value;render();}if(ev.target.id==='scopeInput'){scope=ev.target.value;render();}});
document.addEventListener('input',ev=>{if(ev.target.id==='sourceSearch'){const start=ev.target.selectionStart;search=ev.target.value;render();const input=document.querySelector('#sourceSearch');input.focus();input.setSelectionRange(start,start);}});
async function init(){for(const key of Object.keys(data))data[key]=await store.get(key,[]);render();}init().catch(err=>{console.error(err);el.innerHTML=`<div class="notice">로컬 데이터베이스를 열 수 없습니다: ${e(err.message)}</div>`;});
